name = "glesia"
version = "1.1.0"
description = "Safe-ish Gleam bindings for Erlang Mnesia"
licences = ["MIT"]
repository = { type = "github", user = "rjpruitt16", repo = "glesia" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
